//
// ArtworksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ArtworksAPI {

    /**
     Get artwork by ID
     
     - parameter id: (path) Unique identifier of the artwork 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ArtworkResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getArtworkById(id: Int, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .art)) async throws(ErrorResponse) -> ArtworkResponse {
        return try await getArtworkByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get artwork by ID
     - GET /artworks/{id}
     - Retrieve detailed information about a specific artwork
     - parameter id: (path) Unique identifier of the artwork 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ArtworkResponse> 
     */
    open class func getArtworkByIdWithRequestBuilder(id: Int, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .art)) -> RequestBuilder<ArtworkResponse> {
        var localVariablePath = "/artworks/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ArtworkResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get paginated list of artworks
     
     - parameter page: (query) Page number for pagination (optional, default to 1)
     - parameter limit: (query) Number of items per page (optional, default to 10)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ArtworksResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getArtworks(page: Int? = nil, limit: Int? = nil, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .art)) async throws(ErrorResponse) -> ArtworksResponse {
        return try await getArtworksWithRequestBuilder(page: page, limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get paginated list of artworks
     - GET /artworks
     - Retrieve a paginated list of artworks from Art Institute of Chicago
     - parameter page: (query) Page number for pagination (optional, default to 1)
     - parameter limit: (query) Number of items per page (optional, default to 10)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ArtworksResponse> 
     */
    open class func getArtworksWithRequestBuilder(page: Int? = nil, limit: Int? = nil, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .art)) -> RequestBuilder<ArtworksResponse> {
        let localVariablePath = "/artworks"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ArtworksResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
