//
// DisneyCharactersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DisneyCharactersAPI {

    /**
     Get Disney character by ID
     
     - parameter id: (path) Unique identifier of the character 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DisneyCharacter
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getDisneyCharacterById(id: Int, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .disney)) async throws(ErrorResponse) -> DisneyCharacter {
        return try await getDisneyCharacterByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Disney character by ID
     - GET /character/{id}
     - Retrieve detailed information about a specific Disney character
     - parameter id: (path) Unique identifier of the character 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DisneyCharacter> 
     */
    open class func getDisneyCharacterByIdWithRequestBuilder(id: Int, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .disney)) -> RequestBuilder<DisneyCharacter> {
        var localVariablePath = "/character/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Cache-Control": "no-cache"
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisneyCharacter>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get paginated list of Disney characters
     
     - parameter page: (query) Page number for pagination (optional, default to 1)
     - parameter pageSize: (query) Number of items per page (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DisneyCharactersResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getDisneyCharacters(page: Int? = nil, pageSize: Int? = nil, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .disney)) async throws(ErrorResponse) -> DisneyCharactersResponse {
        return try await getDisneyCharactersWithRequestBuilder(page: page, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get paginated list of Disney characters
     - GET /character
     - Retrieve a paginated list of Disney characters
     - parameter page: (query) Page number for pagination (optional, default to 1)
     - parameter pageSize: (query) Number of items per page (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DisneyCharactersResponse> 
     */
    open class func getDisneyCharactersWithRequestBuilder(page: Int? = nil, apiConfiguration: DisneyAPIAPIConfiguration = DisneyAPIAPIConfiguration.shared(type: .disney)) -> RequestBuilder<DisneyCharactersResponse> {
        let localVariablePath = "/character"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true)
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Cache-Control": "no-cache"
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisneyCharactersResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
