//
// ArtworkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtworkResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var data: Artwork?
    public var info: JSONValue?
    public var config: JSONValue?

    public init(data: Artwork? = nil, info: JSONValue? = nil, config: JSONValue? = nil) {
        self.data = data
        self.info = info
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case info
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(info, forKey: .info)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

