//
// Color.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtColor: Sendable, Codable, ParameterConvertible, Hashable {

    public var h: Int?
    public var l: Int?
    public var s: Int?
    public var percentage: Double?
    public var population: Int?

    public init(h: Int? = nil, l: Int? = nil, s: Int? = nil, percentage: Double? = nil, population: Int? = nil) {
        self.h = h
        self.l = l
        self.s = s
        self.percentage = percentage
        self.population = population
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case h
        case l
        case s
        case percentage
        case population
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(h, forKey: .h)
        try container.encodeIfPresent(l, forKey: .l)
        try container.encodeIfPresent(s, forKey: .s)
        try container.encodeIfPresent(percentage, forKey: .percentage)
        try container.encodeIfPresent(population, forKey: .population)
    }
}

