//
// DimensionsDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DimensionsDetail: Sendable, Codable, ParameterConvertible, Hashable {

    public var depth: Int?
    public var width: Int?
    public var height: Int?
    public var diameter: Int?
    public var clarification: String?

    public init(depth: Int? = nil, width: Int? = nil, height: Int? = nil, diameter: Int? = nil, clarification: String? = nil) {
        self.depth = depth
        self.width = width
        self.height = height
        self.diameter = diameter
        self.clarification = clarification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case depth
        case width
        case height
        case diameter
        case clarification
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(depth, forKey: .depth)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(diameter, forKey: .diameter)
        try container.encodeIfPresent(clarification, forKey: .clarification)
    }
}

