//
// DisneyCharacter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DisneyCharacter: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int
    public var films: [String]?
    public var shortFilms: [String]?
    public var tvShows: [String]?
    public var videoGames: [String]?
    public var parkAttractions: [String]?
    public var allies: [String]?
    public var enemies: [String]?
    public var name: String?
    public var imageUrl: String?
    public var url: String?

    public init(id: Int, films: [String]? = nil, shortFilms: [String]? = nil, tvShows: [String]? = nil, videoGames: [String]? = nil, parkAttractions: [String]? = nil, allies: [String]? = nil, enemies: [String]? = nil, name: String? = nil, imageUrl: String? = nil, url: String? = nil) {
        self.id = id
        self.films = films
        self.shortFilms = shortFilms
        self.tvShows = tvShows
        self.videoGames = videoGames
        self.parkAttractions = parkAttractions
        self.allies = allies
        self.enemies = enemies
        self.name = name
        self.imageUrl = imageUrl
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case films
        case shortFilms
        case tvShows
        case videoGames
        case parkAttractions
        case allies
        case enemies
        case name
        case imageUrl
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(films, forKey: .films)
        try container.encodeIfPresent(shortFilms, forKey: .shortFilms)
        try container.encodeIfPresent(tvShows, forKey: .tvShows)
        try container.encodeIfPresent(videoGames, forKey: .videoGames)
        try container.encodeIfPresent(parkAttractions, forKey: .parkAttractions)
        try container.encodeIfPresent(allies, forKey: .allies)
        try container.encodeIfPresent(enemies, forKey: .enemies)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

