//
// DisneyPaginationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DisneyPaginationInfo: Sendable, Codable, ParameterConvertible, Hashable {

    public var count: Int
    public var totalPages: Int
    public var previousPage: String?
    public var nextPage: String?

    public init(count: Int, totalPages: Int, previousPage: String? = nil, nextPage: String? = nil) {
        self.count = count
        self.totalPages = totalPages
        self.previousPage = previousPage
        self.nextPage = nextPage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case totalPages
        case previousPage
        case nextPage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encodeIfPresent(previousPage, forKey: .previousPage)
        try container.encodeIfPresent(nextPage, forKey: .nextPage)
    }
}

