//
// DisneyCharactersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DisneyCharactersResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var info: DisneyPaginationInfo?
    public var data: [DisneyCharacter]

    public init(info: DisneyPaginationInfo, data: [DisneyCharacter]) {
        self.info = info
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case info
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(info, forKey: .info)
        try container.encode(data, forKey: .data)
    }
}

