//
// Thumbnail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Thumbnail: Sendable, Codable, ParameterConvertible, Hashable {

    public var lqip: String?
    public var width: Int?
    public var height: Int?
    public var altText: String?

    public init(lqip: String? = nil, width: Int? = nil, height: Int? = nil, altText: String? = nil) {
        self.lqip = lqip
        self.width = width
        self.height = height
        self.altText = altText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lqip
        case width
        case height
        case altText = "alt_text"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lqip, forKey: .lqip)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(altText, forKey: .altText)
    }
}

